version: "3"

services:
  gotify:
    image: gotify/server
    #user: 1000:1000
    ports:
      - 8080:80
    environment:
      - GOTIFY_DEFAULTUSER_PASS=custom
    volumes:
      - "./gotify_data:/app/data"
